### ISSUE TITLE
如果现在开始实现一个后端 作者考虑什么技术栈？

### ISSUE THREAD

**Issue by Code-Agitator** [LRQ-front/surveyEase_mock#1]
我是一名javaer，但是我也做过node、Python等语言的项目，最近有个需求想做一个类似的简单的问卷系统。我想我可以帮忙设计后端相关的内容，所以我想问下作者在后端方面有没有过什么设想。

**Comment by Arlrq** [comment]
koa吧，就用过node，不过目前没什么时间做
